name: Build Application

on: [push, pull_request]

jobs:

#  build-docker-image:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag doodleverse:$(date +%s)

  build:
    name: Build the Application
    runs-on: ubuntu-latest
    env:
      PORT: 8080
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package