name: Deploy Image to Docker Hub

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

on:
  workflow_run:
    workflows: [ "Build Application" ]
    types: [ completed ]
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag doodleverse:$(date +%s)

#  test:
#    name: Test the Application
#    runs-on: ubuntu-latest
#    env:
#      PORT: 8000
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#      - name: Test with Maven
#        run: mvn clean test

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build, test ]

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/doodleverse .
      - name: Docker push
        run: docker push ${{secrets.DOCKER_USERNAME}}/doodleverse